version: "3.9"

services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tickerq_2.5.0_1
    ports:
      - "5432:5432"
    networks:
      - app-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  dashboard:
    build:
      context: .
      dockerfile: src/Dashboard/Dockerfile
    container_name: dashboard
    depends_on:
      postgres-db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - app-net
    environment:
      DOTNET_RUNNING_IN_CONTAINER: true
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false

  node:
    build:
      context: .
      dockerfile: src/Node/Dockerfile
    depends_on:
      postgres-db:
        condition: service_healthy
      dashboard:
        condition: service_started
    networks:
      - app-net
    environment:
      DOTNET_RUNNING_IN_CONTAINER: true
      DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
    deploy:
      replicas: 3   # поднимаем 3 экземпляра Node

networks:
  app-net:
    driver: bridge
